# -*- coding: utf-8 -*-
"""GITHUB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wK-mXsHi9ImLEV2PvjMVhqyRlHlP_kQg
"""

import streamlit as st

st.title("Mi primera aplicacion en streamlist")
st.header("Este es mi encabezado")
st.subheader("Este es un subtitulo")
st.write("Esta es una introduccion a streamlist, donde exploraremos como hacer aplicaciones interactivas")
